{% set name = "py-xid" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/py-xid-{{ version }}.tar.gz
  sha256: 82e5bbdab92d104fcc2bcb95a169ecaf126e72f838f0da6900efd9a1323ed05f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner >=5.2
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - xid
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/alexferl/xid
  license: MIT
  license_file: LICENSE
  summary: Globally Unique Identifier generator library. A Python port of rs/xid

extra:
  recipe-maintainers:
    - mariusvniekerk
